# Site
name: "Coderator"
title: "Coderator"
description: "Software design, development and tutorial"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: /home
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  majid:
    name: Majid Abarghooei
    display_name: Majid Abarghooei
    gravatar: 274bb957225edadd028e86e52c2e0040
    email: abarghooeimajid@gmail.com
    web: https://coderator.dev
    twitter: https://twitter.com/dante0747
    description: "A software developer who still has his dreams to move the world forward!"

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

# Archives
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
